### ISSUE TITLE
Advise users to uninstall other "Extra" plugins before installing the Tool Pack 

### ISSUE THREAD

**Issue by Javaru** [jonathanlermitage/ij-extra-all-plugins-pack-pub#2]
You may want to instruct/advise users to uninstall your other plugins prior it installing the  _Extra Tools Pack._ As a long time user, I had _Extra Icons_ installed when I purchased and installed the _Tools Pack_. When I restarted IntelliJ IDEA (v2024.1), it refused to start with the below exception occurring. I had to manually uninstall _Extra Icons_ by deleting it from the plugins directory on my file system. Ideal, it would be nice to warn about this at installation time.

Looking forward to using the features provided by the addition of as _Extra IDE Tweaks_ and _Extra ToolWindow Colorful Icons_ via the _Extra Tools Pack_.

```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: lermitage.intellij.extra.icons.cfg.services.SettingsIDEService [Plugin: lermitage.intellij.extra.icons]
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:572)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:333)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents$default(ComponentManagerImpl.kt:315)
    at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$initServiceContainerJob$1$1.invokeSuspend(ApplicationLoader.kt:102)
    at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$initServiceContainerJob$1$1.invoke(ApplicationLoader.kt)
    at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$initServiceContainerJob$1$1.invoke(ApplicationLoader.kt)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
    at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
    at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
    at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$initServiceContainerJob$1.invokeSuspend(ApplicationLoader.kt:101)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.platform.instanceContainer.internal.InstanceAlreadyRegisteredException: lermitage.intellij.extra.icons.cfg.services.SettingsIDEService
    at com.intellij.platform.instanceContainer.internal.InstanceRegistrarImpl.registerInitializer(InstanceRegistrarImpl.kt:32)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2Inner(ComponentManagerImpl.kt:628)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:565)
    ... 21 more

-----
Your JRE: 17.0.11+1-b1207.24 aarch64 (JetBrains s.r.o.)
/Users/Redacted/Applications/IntelliJ IDEA Ultimate.app/Contents/jbr/Contents/Home
```

**Comment by jonathanlermitage** [comment]
Hi, thanks for your feedback. Yeah, these plugins are marked as incompatible, so the IDE is _supposed_ to disable both plugins, and show an error in the Plugins manager. Unfortunately, it doesn't work super well, and it can lead to the worst scenario: the IDE can't start. I'm very sorry for that. I will open an issue in the IntelliJ's bug-tracker.   
I will see how to inform users about this problem. I will mention this in the plugin's description, but I'm wondering if plugins (like Extra Icons) should also display a notification saying users should uninstall (Extra Icons) if they wish to install Extra Tools Pack.

**Comment by jonathanlermitage** [comment]
OMG, I am an idiot, Extra Icons' ID is `lermitage.intellij.extra.icons`, but I marked Extra Tools Pack incompatible with `lermitage.ij.extra.icons`. This explains why the IDE lets you install both plugins. Very sorry for that. I will publish a plugin update asap.

**Comment by jonathanlermitage** [comment]
Published a new plugin release to the JetBrains marketplace. It should be available next Tuesday. Or this evening if I'm lucky. JetBrains validates plugins within 2 business days, but sometimes this is much faster.  
[Extra Tools Pack-2024.7.2.zip](https://github.com/user-attachments/files/16475911/Extra.Tools.Pack-2024.7.2.zip)

**Comment by Javaru** [comment]
Glad it was something simple. As the king of bugs due to typos, I can relate. Thanks for the fast turnaround time.
